name: Run Crawling

on:
  workflow_dispatch:

jobs:
  crawling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run crawling
        run: python crawling.py
      - name: Save Excel
        uses: actions/upload-artifact@v4
        with:
          name: stock-list
          path: 상장법인목록.xlsx
